# This file may be used to create an environment using:
# $ conda env create --file environment.yml
# platform: linux-64
name: somatic-RNA-variant-callers
channels:
  - bioconda
  - conda-forge
dependencies:
  - black=23.3.0
  - peppy=0.35.5
  - pytest-workflow=1.6.0
  - python=3.10.2
  - snakemake-minimal=7.25.0
  - snakefmt=0.8.4
  - xopen=0.7.3
